### ISSUE TITLE
Build failed in Lastest react-native

### ISSUE THREAD

**Issue by themehdihn** [5-stones/react-native-readium#48] opened 2024-03-06 10:05 UTC
With these specifications, I tried to install the build.gradle  and the latest version of React Native, but I failed to get the build.
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin")
    }
}

I encountered the following errors:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
     Required by:
         project :app > project :react-native-readium > com.github.readium.kotlin-toolkit:readium-navigator:2.2.1
      > Could not resolve com.github.barteksc:android-pdf-viewer:2.8.2.
         > Could not get resource 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/barteksc/android-pdf-viewer/2.8.2/android-pdf-viewer-2.8.2.pom'. Received status code 401 from server: Unauthorized
   > Could not find com.duolingo.open:rtl-viewpager:1.0.3.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/duolingo/open/rtl-viewpager/1.0.3/rtl-viewpager-1.0.3.pom
       - https://repo.maven.apache.org/maven2/com/duolingo/open/rtl-viewpager/1.0.3/rtl-viewpager-1.0.3.pom   
       - file:/C:/Users/UP/Desktop/tessset/ZiBook/node_modules/jsc-android/dist/com/duolingo/open/rtl-viewpager/1.0.3/rtl-viewpager-1.0.3.pom
       - https://dl.google.com/dl/android/maven2/com/duolingo/open/rtl-viewpager/1.0.3/rtl-viewpager-1.0.3.pom       - https://www.jitpack.io/com/duolingo/open/rtl-viewpager/1.0.3/rtl-viewpager-1.0.3.pom
     Required by:
         project :app > project :react-native-readium > com.github.readium.kotlin-toolkit:readium-navigator:2.2.1
   > Could not find com.shopgun.android:utils:1.0.9.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
       - https://repo.maven.apache.org/maven2/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
       - file:/C:/Users/UP/Desktop/tessset/ZiBook/node_modules/jsc-android/dist/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
       - https://dl.google.com/dl/android/maven2/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
       - https://www.jitpack.io/com/shopgun/android/utils/1.0.9/utils-1.0.9.pom
     Required by:
         project :app > project :react-native-readium > com.github.readium.kotlin-toolkit:readium-navigator:2.2.1

What is wrong???

**Comment by jspizziri** [comment] 2024-03-06 10:19
Closing as a duplicate of https://github.com/5-stones/react-native-readium/issues/47

**Closed by jspizziri** 2024-03-06 10:19 UTC
