### ISSUE TITLE
[Bug] Scroll setting is not working properly on Android

### ISSUE THREAD

**Issue by M-HARIS-97** [5-stones/react-native-readium#23] opened 2022-12-15 08:48 UTC
Please check the following video;

https://user-images.githubusercontent.com/57429370/207814193-abd50882-ebb3-4183-883a-e340d9d67b6b.mp4

**Comment by jspizziri** [comment] 2022-12-15 10:02
@M-HARIS-97  please create a reproduction in the example app. I haven't seen this before.

**Comment by M-HARIS-97** [comment] 2022-12-20 11:54
@jspizziri This epub has `overflow-x: hidden` CSS for the` <body>` tag. That is what is causing this.

**Comment by jspizziri** [comment] 2022-12-20 12:15
@M-HARIS-97 glad you sorted it out.

**Comment by mickael-menu** [comment] 2022-12-20 13:56
This particular issue should be fixed in the next version of the Kotlin toolkit, see https://github.com/readium/kotlin-toolkit/pull/294

**Comment by mickael-menu** [comment] 2022-12-20 14:38
I found this wrapper [thanks to you actually](https://github.com/readium/swift-toolkit/issues/263) 😄 I'm subscribed to the activity now.

Feel free to come participate in our bi-weekly Zoom calls or API discussions on Slack and the Readium repos. The more the merrier!

**Comment by jspizziri** [comment] 2022-12-20 15:19
@mickael-menu I just might do that! Where can I find the invite links?

**Comment by mickael-menu** [comment] 2022-12-20 15:26
You should receive a Slack invitation by mail soon, let me know if you don't. Our Zoom calls are notified on the #general channel but we're taking a break until end of January to figure out what's the best timing and cast.

**Comment by jspizziri** [comment] 2023-01-03 17:25
@M-HARIS-97 [`kotlin-tooklit` `2.3.0` has been released](https://github.com/readium/kotlin-toolkit/releases/tag/2.3.0). As mentioned above the fix for this issue is contained in that release.

What remains to be done is to upgrade this library to use that version. Based on [the migration guide](https://github.com/readium/kotlin-toolkit/blob/2.3.0/docs/migration-guide.md#230) it looks like there are several changes we'll need to make (specifically to how preferences work) in order to upgrade.

I encourage you to investigate and put together a PR if you need this fix soon. As for our team, it will probably be a while before it falls on our roadmap.

**Comment by mickael-menu** [comment] 2023-01-04 08:27
The changes regarding the Preferences API and the HTTP server are optional in 2.3.0. However the `Decoration.extras` and PDF support sections in the migration guide are required to upgrade.

**Comment by jspizziri** [comment] 2024-07-26 18:21
@M-HARIS-97 i've just merged [an upgrade to kotlin-toolkit@2.4.1](https://github.com/5-stones/react-native-readium/pull/60), which should resolve this issue.

**Closed by jspizziri** 2024-07-26 18:21 UTC
Labels: bug, Platform: Android, dependencies
